Haz repo clase 1
IslasGECI/eradication_success_assessment pull request #1
Opened 2020-07-10 07:06 UTC by nepito

2020-07-22 22:44 UTC, MaritzaB commented
Listo @evaristor ya están palomeados todos los puntos del checklist.

2020-07-22 22:48 UTC, evaristor commented
Muchas gracias, @MaritzaB, por verificar los requisitos.
@nepito: Yo reviso la tarea.

2020-07-28 15:51 UTC, devarops requested changes
Aquí dejo mi primer revisión.

2020-07-28 15:51 UTC, devarops commented on eradication_success_assessment/get_required_effort.py
> +    print("v0.1.0")
Esto parece código repetido (ver línea 5 de `setup.py`). Tal vez [esto](https://stackoverflow.com/questions/2058802/) sirva de algo.
```suggestion
    ver = pkg_resources.require("eradication_success_assessment")[0].version
    print(ver)
```
Falta pone el `import pkg_resources` en algún lugar.

2020-07-28 15:51 UTC, devarops commented on setup.py
> +)
Por favor podrías agregar fin de línea a la última línea?
```suggestion
)

```

2020-07-28 15:51 UTC, evaristor commented on eradication_success_assessment/get_required_effort.py
> +valores extremos de tipo I, II y III:
Por favor podrías quitar los espacios del final de las líneas?
```suggestion
Utilizamos la función de distribución de valores extremos generalizada (GEV, por sus siglas en
inglés) para modelar la probabilidad de éxito en la erradiación de rata a partir de las
observaciones en cámaras trampa. La GEV es una familia de funciones continuas de probabilidad que
combina las funciones de Gumbel, Fréchet y Weibull, conocidas como funciones de distribución de
valores extremos de tipo I, II y III:
```

2020-07-28 15:51 UTC, evaristor commented on eradication_success_assessment/get_required_effort.py
> +    \subsection*{Análisis}
Veo que abajo usaste dobles digonales invertidas `\\`. ¿Aquí no se necesitan?
```suggestion
    \\subsection*{Análisis}
```

2020-07-28 15:51 UTC, evaristor commented on eradication_success_assessment/get_required_effort.py
> +la probabilidad del éxito en la erradicación será mayor.
¿Por favor podrías quitar los espacios del final de las líneas?
```suggestion
Considerando los esfuerzos entre avistamientos, definimos la probabilidad de obtener una captura
dependiendo del esfuerzo dado. De manera similar, podemos saber cuál es el esfuerzo necesario para
tener una probabilidad de éxito de erradicación deseada. A mayor esfuerzo, sin evidencia de rata, la
probabilidad del éxito en la erradicación será mayor.
```

2020-07-28 15:51 UTC, evaristor commented on eradication_success_assessment/get_required_effort.py
> +$\\alpha=$\\py{'%4.2f'% effort['significance_level']}.
Por favor podrías quitar los espacios del final de las líneas?
```suggestion
Calculamos el esfuerzo necesario para alcanzar una probabilidad de
\\py{'%4.1f'% success_probability}\\%
en el éxito de la erradicación, con un nivel de significancia del
$\\alpha=$\\py{'%4.2f'% effort['significance_level']}.
```

2020-07-28 15:51 UTC, evaristor commented on eradication_success_assessment/get_required_effort.py
> +def make_fit(data, capture_date, seed, n_bootstrapping):
[OPCIONAL] Checa [esto](https://learning.oreilly.com/library/view/clean-code/9780136083238/chapter03.html#ch3lev1sec6):
> The ideal number of arguments for a function is zero (niladic). Next comes one (monadic), followed closely by two (dyadic). Three arguments (triadic) should be avoided where possible. More than three (polyadic) requires very special justification—and then shouldn’t be used anyway.
~ Tío Bob

2020-07-28 15:59 UTC, evaristor commented on eradication_success_assessment/get_required_effort.py
> +def make_fit(data, capture_date, seed, n_bootstrapping):
¿Tal vez la función está demasiado larga?

2020-08-06 02:41 UTC, nepito commented on eradication_success_assessment/get_required_effort.py
> +    \subsection*{Análisis}
Aquí no se necestan pero obtenemos el mismo resultado si se lo ponemos, así que se lo pondré

2020-08-06 02:42 UTC, nepito commented on eradication_success_assessment/get_required_effort.py
> +    print("v0.1.0")
Agregué `import pkg_resources` al incio de este archivo

2020-08-07 16:10 UTC, evaristor commented
@nepito @islasfernando Parece que no nos pusimos de acuerdo:

Quedamos en que esto: `pkg_resources.require("eradication_success_assessment")[0].version` lo usaríamos en la prueba en lugar de usarlo en `eradication_success_assessment/get_required_effort.py` ya que ahí sobrevive un mutante. ¿Quieres que te eche la mano @islasfernando?

2020-08-07 16:12 UTC, islasfernando commented
> @nepito @islasfernando Parece que no nos pusimos de acuerdo:
> 
> Quedamos en que esto: `pkg_resources.require("eradication_success_assessment")[0].version` lo usaríamos en la prueba en lugar de usarlo en `eradication_success_assessment/get_required_effort.py` ya que ahí sobrevive un mutante. ¿Quieres que te eche la mano @islasfernando?

En el `eradication_success_assessment/get_required_effort.py` que va entonces?

2020-08-07 16:13 UTC, islasfernando commented
Le puse close en vez de comment...

2020-08-07 16:13 UTC, evaristor commented
> Le puse close en vez de comment...

:rofl:

2020-08-07 16:14 UTC, evaristor commented
> Le puse close en vez de comment...

:rofl:

2020-08-20 21:33 UTC, islasfernando approved these changes

2020-08-20 21:34 UTC, merged